Remove travis configuration

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -3,12 +3,14 @@ name: build
 on:
   push:
     branches: ['*']
+    tags:        
+      - v*
   pull_request:
     type: [opened, reopened, edited]
 
 jobs:
   test:
-    name: '${{matrix.name}} - puppet (${{matrix.puppet}}) '
+    name: '${{matrix.name}} - puppet (${{matrix.puppet}})'
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -52,3 +54,39 @@ jobs:
           bundle install --without system_tests --path=${BUNDLE_PATH:-vendor/bundle}
       - name: Test
         run: 'bundle exec rake $CHECK'
+
+  deploy:
+    name: 'deploy to forge'
+    needs: test
+    runs-on: ubuntu-latest
+    # TODO uncomment once we get this working
+    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Setup Ruby
+        uses: actions/setup-ruby@v1
+        with:
+          ruby-version: '2.5'
+      - name: Bundle prep
+        run: |
+          gem install bundler
+          bundle -v
+          rm -f Gemfile.lock
+          # Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
+          # See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
+          # Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
+          [ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION
+          gem --version
+          bundle -v
+      - name: Gem install
+        run: 'gem install rake puppet-blacksmith'
+      - name: Build and Deploy
+        env:
+          # TODO configure secrets here:
+          #  https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
+          BLACKSMITH_FORGE_USERNAME: myuser
+          BLACKSMITH_FORGE_PASSWORD: mypassword
+        run: |
+          rake module:build
+          rake module:push
